# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-17 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Law',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('summary', models.CharField(max_length=500)),
                ('created_date', models.DateField()),
                ('issued_date', models.DateField()),
                ('is_active', models.IntegerField()),
                ('law_type', models.IntegerField(choices=[(1, 'Emendas \xe0 Constitui\xe7\xe3o'), (2, 'leis complementares'), (3, 'leis ordin\xe1rias'), (4, 'leis delegadas'), (5, 'medidas provis\xf3rias'), (6, 'decretos legislativos'), (7, 'resolu\xe7\xf5es')], default=3)),
                ('created_by', models.CharField(max_length=30)),
                ('politic_author', models.CharField(max_length=30)),
            ],
        ),
    ]
