# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-17 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='law',
            old_name='politic_author',
            new_name='politician_author',
        ),
        migrations.AddField(
            model_name='law',
            name='city',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='law',
            name='text',
            field=models.CharField(default=1, max_length=60000),
            preserve_default=False,
        ),
    ]
