# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0002_auto_20180317_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='law_type',
            field=models.CharField(max_length=50),
        ),
    ]
