# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0003_auto_20180319_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='law',
            name='politician_author',
        ),
    ]
