# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0004_remove_law_politician_author'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='law',
            unique_together=set([('city', 'number')]),
        ),
    ]
