# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0005_auto_20180319_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='law_url',
            field=models.URLField(blank='true', null='true'),
        ),
    ]
