# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-19 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0006_law_law_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='city',
            field=models.CharField(blank='true', max_length=50, null='true'),
        ),
        migrations.AlterField(
            model_name='law',
            name='created_by',
            field=models.CharField(blank='true', max_length=30, null='true'),
        ),
        migrations.AlterField(
            model_name='law',
            name='created_date',
            field=models.DateField(blank='true', null='true'),
        ),
        migrations.AlterField(
            model_name='law',
            name='is_active',
            field=models.IntegerField(blank='true', null='true'),
        ),
        migrations.AlterField(
            model_name='law',
            name='issued_date',
            field=models.DateField(blank='true', null='true'),
        ),
        migrations.AlterField(
            model_name='law',
            name='law_type',
            field=models.CharField(blank='true', max_length=50, null='true'),
        ),
        migrations.AlterField(
            model_name='law',
            name='number',
            field=models.CharField(blank='true', max_length=10, null='true'),
        ),
        migrations.AlterField(
            model_name='law',
            name='summary',
            field=models.CharField(blank='true', max_length=500, null='true'),
        ),
        migrations.AlterField(
            model_name='law',
            name='text',
            field=models.CharField(blank='true', max_length=60000, null='true'),
        ),
    ]
