# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-14 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0009_law_law_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='law',
            unique_together=set([('city', 'number', 'issued_date')]),
        ),
    ]
