# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-01-14 13:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('law', '0010_auto_20190114_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='scrapped_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2019, 1, 14, 13, 42, 4, 739934, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
