# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('site_url', models.CharField(max_length=200)),
                ('city_xpath', models.CharField(blank='true', max_length=200, null='true')),
                ('law_number_xpath', models.CharField(blank='true', max_length=200, null='true')),
                ('summary_xpath', models.CharField(blank='true', max_length=200, null='true')),
                ('created_date_xpath', models.CharField(blank='true', max_length=200, null='true')),
                ('issued_date_xpath', models.CharField(blank='true', max_length=200, null='true')),
                ('law_type_xpath', models.CharField(blank='true', max_length=200, null='true')),
                ('created_by_xpath', models.CharField(blank='true', max_length=200, null='true')),
                ('politician_author_xpath', models.CharField(blank='true', max_length=200, null='true')),
                ('law_url_xpath', models.CharField(blank='true', max_length=200, null='true')),
            ],
        ),
    ]
