# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-18 01:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrape', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrape',
            name='site_parameter_end',
            field=models.IntegerField(blank='true', null='true'),
        ),
        migrations.AddField(
            model_name='scrape',
            name='site_parameter_name',
            field=models.CharField(blank='true', max_length=100, null='true'),
        ),
        migrations.AddField(
            model_name='scrape',
            name='site_parameter_start',
            field=models.IntegerField(blank='true', null='true'),
        ),
    ]
